[package]
name = "awesome-rewrite-it-in-rust"
version = "0.1.0"
authors = ["Takayuki Maeda <takoyaki0316@gmail.com>"]
edition = "2018"
homepage = "https://github.com/TaKO8Ki/awesome-rewrite-it-in-rust"
repository = "https://github.com/TaKO8Ki/awesome-rewrite-it-in-rust"
license = "MIT"
default-run = "awesome-rewrite-it-in-rust"

[dependencies]
anyhow = "1"
pulldown-cmark = "0.13"
futures = "0.3"
reqwest = { version = "0.13", default-features = false, features = ["charset", "hickory-dns", "rustls"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
env_logger = "0.11"
log = "0.4"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.2"
